import Component from './component.vue'
import registerTemplate from '~/server/utils/template-registry'
import { z } from 'zod'
import parseMarkdown from '~/server/utils/parse-markdown.ts'
import { type ParsedTerm } from '~/server/utils/parse-markdown.ts'

export const contractSchema = z.object({
  contact: z.object({
    name: z.string(),
    title: z.string(),
    address: z.string(),
    email: z.email('Invalid client email'),
    phone: z.string(),
  }),
  project: z.object({
    title: z.string(),
    quoteNumber: z.string(),
    quoteDate: z.date(),
    shootDate: z.date(),
    shootLocation: z.string(),
    callTime: z.iso.time(),
  }),
  deliverables: z.array(z.string()),
  totalAmount: z.number(),
  advancePercentage: z.number().min(0).max(100).optional(),
  agreementDate: z.date(),
  expiresIn: z.date(),
  terms: z.object({
    content: z.string(),
    lastUpdated: z.date(),
  }),
  organization: z.object({
    id: z.string(),
    name: z.string(),
    legalName: z.string(),
    entityType: z.enum(['LLP', 'Private Limited', 'Proprietorship']),
    tradeRelationship: z.enum(['Primary', 'Trading As', 'Operating Division', 'Wholly-Owned Subsidiary', 'Special Purpose Vehicle']),
    gstin: z.string().optional(),
    pan: z.string().optional(),
    address: z.string(),
    foundedYear: z.number(),
    accountDetails: z.object({
      accountName: z.string(),
      accountNumber: z.number(),
      bankName: z.string(),
      ifscCode: z.string(),
    }),
    branding: z.object({
      logo: z.string(),
      color: z.object({
        primary: z.string(),
        accent: z.string(),
      }),
      font: z.string(),
    }),
    website: z.string().optional(),
    phone: z.string().optional(),
    contactEmail: z.email(),
    billingEmail: z.email(),
    whatsapp: z.string().optional(),
    socials: z.record(z.any(), z.any()).optional(),
    primaryContactId: z.string(),
    organizationMemberIds: z.array(z.string()),
    createdAt: z.string(),
    updatedAt: z.string(),
  }),
})

export type ContractPayload = z.infer<typeof contractSchema>

const placeholders: ContractPayload = {
  contact: {
    name: 'Jane Doe',
    title: 'Lead Cinematographer',
    address: '1007 Mountain Drive, Gotham',
    email: 'billing@wayne.ent',
    phone: '+1 555-0199',
  },
  project: {
    title: 'Photography and Videography',
    quoteNumber: 'QT-2026-089',
    quoteDate: new Date(),
    shootDate: new Date(),
    shootLocation: 'Gotham City',
    callTime: '08:00 AM',
  },
  deliverables: ['1x 60-second highlight video (4K resolution)', '50 edited high-resolution photographs', 'Delivery of all raw footage and unedited image files'],
  totalAmount: 150_000,
  advancePercentage: 35,
  agreementDate: new Date(),
  expiresIn: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
  terms: {
    content: `### 3. Copyright & Ownership (Work Made for Hire)\n\nAll photographs, videos, raw files, and deliverables created under this Agreement shall be considered a "work made for hire."\n\n- **Company Rights:** RED CAT PICTURES shall be the exclusive owner of all rights, titles, and interests in the media, including all copyrights. The Company has the unrestricted right to use, edit, distribute, and publish the media across all platforms globally and in perpetuity.\n- **Portfolio Rights:** The Service Provider may use the final, publicly released media for their personal portfolio, provided they credit the Company.\n\n### 4. Cancellation & Rescheduling\n\n- **By the Company:** If the Company cancels the shoot within 48 hours of the scheduled call time, the Service Provider shall not be entitled to the balance.\n- **By the Service Provider:** If unable to perform due to emergency, they must secure a replacement of equal skill immediately.\n\n### 5. Independent Contractor Status\n\nThe Service Provider is an independent contractor. Nothing in this Agreement shall be construed to create an employer-employee relationship.\n\n### 6. Liability & Indemnification\n\n- **Data Loss:** The Service Provider shall implement standard dual-card backup protocols. In the unlikely event of total media failure, liability shall be limited to the forfeiture of the agreed fee.`,
    lastUpdated: new Date(),
  },
  organization: {
    id: 'modest-human-brands',
    name: 'RED CAT PICTURES',
    legalName: 'RED CAT PICTURES LLP',
    entityType: 'LLP',
    tradeRelationship: 'Primary',
    gstin: undefined,
    pan: 'ABCDE0123F',
    address: 'Abc Road, Near DEF, UIO - 1890',
    foundedYear: 2020,
    accountDetails: {
      accountName: 'RED CAT PICTURES LLP',
      accountNumber: 1_234_567_890,
      bankName: 'HDFC Bank',
      ifscCode: 'HDFC0001234',
    },
    website: 'https://modesthumanbrands.com',
    contactEmail: 'hello@modesthumanbrands.com',
    billingEmail: 'billing@modesthumanbrands.com',
    primaryContactId: 'contact-1',
    organizationMemberIds: ['member-1'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    branding: {
      logo: 'https://modesthumanbrands.com/logo.svg',
      color: {
        primary: '#2B2B2B',
        accent: '#4A85FF',
      },
      font: 'Exo2',
    },
  },
}

registerTemplate({
  id: 'contract',
  fonts: [
    { name: 'Exo2', path: './asset/Exo2-Regular.ttf' },
    { name: 'Oxanium', path: './asset/Oxanium-Regular.ttf' },
  ],
  schema: contractSchema,
  placeholders,
  component: Component,
  transformPayload: (rawData: ContractPayload) => {
    const p = placeholders
    const org = rawData.organization || p.organization
    const orgBranding = org?.branding || p.organization!.branding
    const rawTerms = rawData.terms?.content || p.terms.content

    const parsedTerms: ParsedTerm[] = parseMarkdown(rawTerms)

    return {
      organizationName: org?.name || p.organization!.name,
      organizationLegalName: org?.legalName || p.organization!.legalName,
      organizationEntityType: org?.entityType || p.organization!.entityType,
      organizationTradeRelationship: org?.tradeRelationship || p.organization!.tradeRelationship,
      organizationGstin: org?.gstin || p.organization!.gstin,
      organizationPan: org?.pan || p.organization!.pan,
      organizationAddress: org?.address || p.organization!.address,
      organizationLogo: orgBranding?.logo || p.organization.branding.logo,
      organizationFont: orgBranding?.font || p.organization!.branding!.font,
      organizationColorPrimary: orgBranding?.color?.primary || p.organization!.branding!.color!.primary,
      organizationColorAccent: orgBranding?.color?.accent || p.organization!.branding!.color!.accent,
      agreementDate: rawData.agreementDate || p.agreementDate,
      contractorName: rawData.contact?.name || p.contact.name,
      contractorRole: rawData.contact?.title || p.contact.title,
      expiresIn: rawData.expiresIn || p.expiresIn,
      projectName: rawData.project?.title || p.project.title,
      shootDates: rawData.project?.shootDate || p.project.shootDate,
      location: rawData.project?.shootLocation || p.project.shootLocation,
      callTime: rawData.project?.callTime || p.project.callTime,
      deliverables: rawData.deliverables && rawData.deliverables.length > 0 ? rawData.deliverables : p.deliverables,
      totalAmount: rawData.totalAmount || p.totalAmount,
      advancePercentage: rawData.advancePercentage ?? p.advancePercentage ?? 35,
      parsedTerms,
    }
  },
  signerFields: [
    {
      id: 'contractor-signature',
      type: 'SIGNATURE',
      signerOrder: 1,
      pageIndex: 'all-except-last',
      x: 405,
      y: 45,
      width: 150,
      height: 40,
      required: true,
    },
    {
      id: 'contractor-signature',
      type: 'SIGNATURE',
      signerOrder: 1,
      pageIndex: -1,
      x: 360 + 10,
      y: 604 - 30,
      width: 150,
      height: 40,
      required: true,
    },
    {
      id: 'contractor-name',
      type: 'NAME',
      signerOrder: 1,
      pageIndex: -1,
      x: 360 + 10,
      y: 556 - 30,
      width: 150,
      height: 40,
      fontSize: 12,
    },
    {
      id: 'contractor-date',
      type: 'DATE',
      signerOrder: 1,
      pageIndex: -1,
      x: 360 + 10,
      y: 508 - 30,
      width: 150,
      height: 40,
      fontSize: 10,
      required: true,
    },
    {
      id: 'contractor-city',
      type: 'TEXT',
      signerOrder: 1,
      pageIndex: -1,
      x: 360 + 10,
      y: 460 - 30,
      width: 150,
      height: 40,
      fontSize: 10,
      required: true,
    },
    {
      id: 'company-signature',
      type: 'SIGNATURE',
      signerOrder: 2,
      pageIndex: -1,
      x: 105 + 10,
      y: 604 - 30,
      width: 150,
      height: 40,
      required: true,
    },
    {
      id: 'company-name',
      type: 'NAME',
      signerOrder: 2,
      pageIndex: -1,
      x: 105 + 10,
      y: 556 - 30,
      width: 150,
      height: 40,
      fontSize: 12,
    },
    {
      id: 'company-date',
      type: 'DATE',
      signerOrder: 2,
      pageIndex: -1,
      x: 105 + 10,
      y: 508 - 30,
      width: 150,
      height: 40,
      fontSize: 10,
      required: true,
    },
    {
      id: 'company-city',
      type: 'TEXT',
      signerOrder: 2,
      pageIndex: -1,
      x: 105 + 10,
      y: 460 - 30,
      width: 150,
      height: 40,
      fontSize: 12,
    },
  ],
})
